# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI
on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: telescope-scriptnames.nvim
          extra-files: |
            lua/telescope-scriptnames/init.lua
